---
prod: &default
  views:
    engine: pug
  checksumhash: md5
  baseUrl: http://compromisos.mybluemix.net
  smtp:
    host: smtp.gmail.com
    port: 465
    secure: true
    auth:
      user: joandelgado18@gmail.com
      pass: pcmxskzxujkforgq
  mysql:
    host: bluemix-sandbox-dal-9-portal.1.dblayer.com
    user: admin
    password: BLDYTBJYRVUBXLDG
    database: compromisos
    port: 29030
dev:
  <<: *default
  port: 8080
  mysql:
    host: localhost
    user: root
    password: mysql
    database: compromisos
    port: 3306
  baseUrl: http://localhost:8080
  smtp:
    host: smtp.gmail.com
    port: 465
    secure: true
    auth:
      user: joandelgado18@gmail.com
      pass: xtyecjonhrbllmno