---
prod: &default
  views:
    engine: pug
  checksumhash: md5
  baseUrl: http://compromisos.mybluemix.net
  smtp:
    host: smtp.gmail.com
    port: 465
    secure: true
    auth:
      user: joandelgado18@gmail.com
      pass: pcmxskzxujkforgq
    from:
      name: NOLAN
      email: joandelgado18@gmail.com
dev:
  <<: *default
  port: 8080
  mysql:
    host: localhost
    user: root
    password: mysql
    database: compromisos
    port: 3306
    debug: false
  baseUrl: http://localhost:8080
  smtp:
    host: smtp.gmail.com
    port: 465
    secure: true
    auth:
      user: joandelgado18@gmail.com
      pass: xtyecjonhrbllmno
    from:
      name: NOLAN
      email: joandelgado18@gmail.com
  objectstorage:
    region: dalas
    useInternal: false
    projectId: eccd3e5be79a49e6aaf39803f3ba0afb
    userId: 8ee69971224c4bd598264fcf5a1f9b35
    username: admin_fec7b1ae06f77932821e8e13b0dfa17ec45a01d1
    password: fMv,n=.hCvacJ^22
    auth:
      interfaceName: public

