---
prod: &default
  views:
    engine: pug
  checksumhash: md5
  baseUrl: http://compromisos.mybluemix.net
  smtp:
    host: smtp.gmail.com
    port: 465
    secure: true
    auth:
      user: joandelgado18@gmail.com
      pass: pcmxskzxujkforgq
    from:
      name: NOLAN Notification
      email: nolan_notification@nolanhub.com
dev:
  <<: *default
  port: 8080
  mysql:
    host: localhost
    user: root
    password: mysql
    database: compose
    port: 3306
    debug: false
  baseUrl: http://localhost:8080
  smtp:
    host: smtp.gmail.com
    port: 465
    secure: true
    auth:
      user: joandelgado18@gmail.com
      pass: xtyecjonhrbllmno
    from:
      name: NOLAN Notification
      email: nolan_notification@nolanhub.com
  objectstorage:
    region: dallas
    useInternal: false
    projectId: ff6c1dbd502840d49c3507d78313f40f
    userId: b9873e8769d9458c852f13d31014248b
    username: admin_efe5b261aa1d5c716d449c3cfdeecd7c8076d880
    password: c(s.3_8v3*gp.FNQ
    auth:
      interfaceName: public
